project:
  type: website
  output-dir: docs

website:
  title: "Wind Resource Temporal Variability"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Data Analysis
      - href: report.qmd
        text: Report
      - href: mrivers_presentation2.qmd
        text: Presentation
    right:
      - icon: github
        href: https://github.com/marierivers/wind_resource_temporal_variability
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
editor: visual



